/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false worker/env.d.ts` (hash: d56f8d359459aecf91945211965fbc67)
interface __BaseEnv_Env {
	OAUTH_KV: KVNamespace;
	ASSETS: Fetcher;
	MCP_ORIGIN: string;
	MCP_ALLOWED_ORIGINS: string;
	MODAL_URL: string;
	SUPABASE_URL: string;
	SUPABASE_PUBLISHABLE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MCP_ORIGIN" | "MCP_ALLOWED_ORIGINS" | "MODAL_URL" | "SUPABASE_URL" | "SUPABASE_PUBLISHABLE_KEY">> {}
}
